# All Rare and Mythic Rare cards in a deck, with set info.
#
# PARAMETERS:
#   ?deck - the deck to query

PREFIX mc:   <urn:stklug84:MagicCardsOntology:2026-02-27#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?cardName ?rarityLabel ?setName WHERE {
  VALUES ?deck { mc:SaheeliRadiantCreatorDeck }

  ?deck mc:hasCard ?c .
  ?c mc:cardName  ?cardName ;
     mc:hasRarity ?r .
  FILTER(?r IN (mc:Rare, mc:MythicRare))
  OPTIONAL { ?r rdfs:label ?rarityLabel }
  OPTIONAL { ?c mc:isInSet ?s . ?s mc:setName ?setName }
}
ORDER BY DESC(?rarityLabel) ?cardName
