#!/usr/bin/env python3
"""Regenerate catalog-v001.xml from the ontology IRIs in the repo.

The knowledge graph resolves its ``owl:imports`` through ``urn:`` IRIs,
which OWL tooling (ROBOT, Protege) cannot dereference. This script scans
every tracked ``*.ttl`` file for its ``owl:Ontology`` declaration and
writes an OASIS XML catalog mapping each ontology IRI to its repo-relative
file path. Relative paths are resolved against the catalog's location, so
the catalog must live in the repository root.

Run from the repository root after adding, removing, or renaming any
ontology file (the ``owl`` CI job fails on unresolvable imports when the
catalog is stale):

    python3 scripts/generate_catalog.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

CATALOG = Path("catalog-v001.xml")
ONTOLOGY_RE = re.compile(r"<(urn:[^>]+)>\s+(?:rdf:type|a)\s+owl:Ontology")


def ontology_iris(root: Path) -> list[tuple[str, str]]:
    """Return (ontology IRI, repo-relative path) for every declaring TTL."""
    entries: list[tuple[str, str]] = []
    for path in sorted(root.rglob("*.ttl")):
        if ".git" in path.parts:
            continue
        match = ONTOLOGY_RE.search(path.read_text(encoding="utf-8"))
        if match:
            entries.append((match.group(1), path.relative_to(root).as_posix()))
    return entries


def render(entries: list[tuple[str, str]]) -> str:
    """Render the OASIS XML catalog document."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by scripts/generate_catalog.py - do not edit by hand.",
        "     Maps the urn: ontology IRIs used in owl:imports to their local",
        "     files so ROBOT/Protege can load the full import closure. -->",
        (
            '<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog"'
            ' prefer="public">'
        ),
    ]
    lines.extend(f'  <uri name="{iri}" uri="{path}"/>' for iri, path in entries)
    lines.append("</catalog>")
    return "\n".join(lines) + "\n"


def main() -> int:
    """Write the catalog and report the entry count."""
    root = Path()
    entries = ontology_iris(root)
    if not entries:
        print("error: no owl:Ontology declarations found", file=sys.stderr)
        return 1
    CATALOG.write_text(render(entries), encoding="utf-8")
    print(f"{CATALOG}: {len(entries)} ontology IRIs mapped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
