# All cards in a deck that are banned in any of the seven tracked formats.
#
# PARAMETERS:
#   ?deck - the deck to query

PREFIX mc:   <urn:stklug84:MagicCardsOntology:2026-02-27#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?cardName ?formatLabel WHERE {
  VALUES ?deck { mc:SaheeliRadiantCreatorDeck }

  ?deck mc:hasCard ?c .
  ?c mc:cardName ?cardName ;
     mc:hasLegality ?lm .
  ?lm mc:inFormat ?fmt ;
      mc:hasLegalityStatus mc:Banned .
  ?fmt rdfs:label ?formatLabel .
}
ORDER BY ?cardName ?formatLabel
